name: Build ImmortalWrt Package

on:
   workflow_dispatch:
  #   inputs:
  #     package_repo:
  #       description: 'Package Git Repository URL'
  #       required: true
  #       default: 'https://github.com/immortalwrt/luci-theme-argon'
  #     version:
  #       description: 'ImmortalWrt Version (e.g: 21.02.7)'
  #       required: true
  #       default: '24.10'
  #
env:
  ipk_repo: https://github.com/muink/homeproxy.git
  ipk_branch: dev/main


jobs:
  build-package:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo -E apt-get -y update
        sudo -E apt-get -y install $(curl -fsSL is.gd/depends_ubuntu_2204)
        sudo -E apt-get -y install zstd clang lld libpcre3 libpcre3-dev clang-15 llvm-15 npm
        export PATH="/usr/bin/clang++:$PATH"

    - name: Download Image Builder
      run: |
        IB_NAME="immortalwrt-imagebuilder-24.10.0-x86-64.Linux-x86_64"
        wget https://downloads.immortalwrt.org/releases/24.10.0/targets/x86/64/$IB_NAME.tar.zst
        tar -I zstd -xvf $IB_NAME.tar.zst
        mv $IB_NAME imagebuilder

    - name: Clone package source
      run: |
        cd imagebuilder
        git clone -b $ipk_branch $ipk_repo package/custom

    - name: Build package
      run: |
        cd imagebuilder
        make -j$(nproc) package/custom/compile V=s

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          imagebuilder/bin/packages/x86_64/base/*.ipk
        tag_name: package-${{ github.run_id }}
        name: Custom Package Build
        body: "Automatically built ImmortalWrt package"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
